version: '3.2'
networks:
  databaseNet:
    external: true

services:
  db:
    image: mysql:5.7
    container_name: appsDB
    restart: always
    ports:
      - '3306:3306'
    environment:
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user-svc-user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'user-svc-password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'user-svc-password'
    networks:
      - databaseNet
    external_links:
      - student-service
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '9090:80'
    environment:
      PMA_HOST: db
    networks:
      - databaseNet